### ISSUE TITLE
XMPP authentication failure - Bosch

### ISSUE THREAD

**Issue by eronnes** [robertklep/nefit-easy-http-server#50] opened 2021-03-09 20:41 UTC
Please advise, can I use this with Bosch EasyControl. I’ve installed befit-easy-http-server, but I see an error in the log:

XMPP authentication failure

**Comment by robertklep** [comment] 2021-03-10 06:35
Duplicate of https://github.com/robertklep/nefit-easy-http-server/issues/30

**Closed as completed by robertklep** 2021-03-10 06:35 UTC
