### ISSUE TITLE
keeps trying to setup connection / loop

### ISSUE THREAD

**Issue by skai21** [robertklep/nefit-easy-http-server#35] opened 2019-07-11 09:12 UTC
Hi / Hoi,

I've installed the easy-server, using all kind of different guides and ways. All without any success at the moment.
When i start the server with: 
env DEBUG=* easy-server --serial=<myserial> --access-key=<myAccessKey --password=<mypassword> --host=localhost --port=3001

it will keep rotating throught the following:
![easy](https://user-images.githubusercontent.com/52780489/61038089-afd2e280-a3cc-11e9-984d-250442e524c1.png)

How can i solve this?

**Comment by robertklep** [comment] 2019-07-11 09:21
Strange, I can't reproduce this myself which rules out an issue with the Nefit/Bosch backend. There seems to be an issue with upgrading the connection to use TLS, but it doesn't say why. You're not using something like PiHole or similar filter that might be causing this?

Can you try and see if the [CLI client](https://github.com/robertklep/nefit-easy-cli) works for you?

**Comment by skai21** [comment] 2019-07-11 09:26
Hi Robert,

I tried env DEBUG=* easy status with my serial, access-key and password.
That gave me the exact same loop, my Pi is default, just domoticz installed and connecte directly to my Fritzbox Router, that has (for as far that i know of) has no firewall towards the internet.

**Comment by robertklep** [comment] 2019-07-11 09:46
Which Node.js version are you using? `node --version`

**Comment by skai21** [comment] 2019-07-11 09:47
v10.16.0

**Comment by robertklep** [comment] 2019-07-11 09:55
That specific version doesn't seem to be causing your problem (it works for me). The 'use lazy socket' message is strange, because if I look at the XMPP code, it suggests that the XMPP client is trying to reconnect. I assume that the Nefit Easy mobile app works for you?

**Comment by skai21** [comment] 2019-07-11 09:57
The App works for me, i'm also looking at my netstat table. the 139.15.227.109 address at port 5222 is Bosch if i'm correct.
It shows me a TIME_WAIT:
tcp        0      0 192.168.178.200:43060   139.15.227.109:5222     TIME_WAIT   -
tcp        0      0 192.168.178.200:43098   139.15.227.109:5222     TIME_WAIT   -
tcp        0      0 192.168.178.200:43106   139.15.227.109:5222     TIME_WAIT   -
tcp        0      0 192.168.178.200:43122   139.15.227.109:5222     TIME_WAIT   -
tcp        0      0 192.168.178.200:43062   139.15.227.109:5222     TIME_WAIT   -
tcp        0      0 192.168.178.200:43132   139.15.227.109:5222     TIME_WAIT   -
tcp        0      0 192.168.178.200:43100   139.15.227.109:5222     TIME_WAIT   -

**Comment by robertklep** [comment] 2019-07-11 10:02
That's normal when the client (in this case) is closing the connection, which supports the reconnection theory. I'll have to delve deeper into the XMPP code (not mine) to see at which point it decides to try and reconnect.

**Comment by skai21** [comment] 2019-07-11 10:42
Thank you, if you need anything tested i'll be here to help you out

**Comment by robertklep** [comment] 2019-07-11 10:57
There's something you can try :)

First, install the server package locally (without `-g`):
```
$ cd /tmp
$ npm i nefit-easy-http-server
```

Then, edit the file `node_modules/node-xmpp-core/lib/Connection.js`. Somewhere around line 17, there's this line:
```
var INITIAL_RECONNECT_DELAY = 1e3
```

Change it to this:
```
var INITIAL_RECONNECT_DELAY = 1e6
```

Then try and see if it works better:
```
env DEBUG=* ./node_modules/.bin/easy-server --serial= --access-key=<myAccessKey --password= --host=localhost --port=3001
```

**Comment by skai21** [comment] 2019-07-11 11:03
xmpp:client:session start socket connection +0ms
  xmpp:connection setup socket +8ms
Error: The maximal backoff delay must be greater than the initial backoff delay.
    at FibonacciBackoffStrategy.BackoffStrategy (/tmp/node_modules/backoff/lib/strategy/strategy.js:35:15)
    at new FibonacciBackoffStrategy (/tmp/node_modules/backoff/lib/strategy/fibonacci.js:15:21)
    at module.exports.fibonacci (/tmp/node_modules/backoff/index.js:23:24)
    at /tmp/node_modules/reconnect-core/index.js:20:67
    at Connection._setupSocket (/tmp/node_modules/node-xmpp-core/lib/Connection.js:123:3)
    at new Connection (/tmp/node_modules/node-xmpp-core/lib/Connection.js:64:8)
    at Client.Session._setupSocketConnection (/tmp/node_modules/node-xmpp-client/lib/session.js:48:21)
    at Client.Session (/tmp/node_modules/node-xmpp-client/lib/session.js:27:10)
    at Client._useStandardConnect (/tmp/node_modules/node-xmpp-client/lib/Client.js:152:11)
    at Client.connect (/tmp/node_modules/node-xmpp-client/lib/Client.js:137:8)
    at connectionPromise.Promise (/tmp/node_modules/nefit-easy-core/lib/index.js:86:12)
    at Promise._execute (/tmp/node_modules/bluebird/js/release/debuggability.js:313:9)
    at Promise._resolveFromExecutor (/tmp/node_modules/bluebird/js/release/promise.js:488:18)
    at new Promise (/tmp/node_modules/bluebird/js/release/promise.js:79:10)
    at NefitEasyCommands.connect (/tmp/node_modules/nefit-easy-core/lib/index.js:67:32)
    at module.exports (/tmp/node_modules/nefit-easy-http-server/lib/cli/index.js:32:17)

**Comment by robertklep** [comment] 2019-07-11 11:04
On the line below, change `var MAX_RECONNECT_DELAY = 30e3` to `var MAX_RECONNECT_DELAY = 30e6`

**Comment by skai21** [comment] 2019-07-11 11:08
Did that, now it runs through 1 loop, and that get stuck:
  xmpp:client:session start socket connection +0ms
  xmpp:connection setup socket +8ms
  xmpp:connection use lazy socket +5ms
  xmpp:connection setup stream +2ms
  xmpp:connection send: <stream:stream xmlns="jabber:client" xmlns:stream="http://etherx.jabber.org/streams" version="1.0" to="wa2-mz36-qrmzh6.bosch.de"> +41ms
  xmpp:connection receive: <?xml version='1.0' encoding='UTF-8'?><stream:stream xmlns:stream="http://etherx.jabber.org/streams" xmlns="jabber:client" from="wa2-mz36-qrmzh6.bosch.de" id="91o8h8pu5b" xml:lang="en" version="1.0"> +21ms
  xmpp:connection receive: <stream:features><starttls xmlns="urn:ietf:params:xml:ns:xmpp-tls"></starttls><mechanisms xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><mechanism>PLAIN</mechanism><mechanism>SCRAM-SHA-1</mechanism><mechanism>DIGEST-MD5</mechanism></mechanisms><ver xmlns="urn:xmpp:features:rosterver"/></stream:features> +17ms
  xmpp:connection send: <starttls xmlns="urn:ietf:params:xml:ns:xmpp-tls"/> +4ms
  xmpp:connection receive: <proceed xmlns="urn:ietf:params:xml:ns:xmpp-tls"/> +19ms
  xmpp:connection use standard socket +45ms
  xmpp:connection setup stream +0ms

**Comment by robertklep** [comment] 2019-07-11 11:11
It still points towards a networking issue, but I'm not sure what's causing it. Can you run `npm ls` in `/tmp` to see which versions of dependencies are installed?

**Comment by skai21** [comment] 2019-07-11 11:13
/tmp
└─┬ nefit-easy-http-server@5.0.2
  ├── bluebird@3.5.5
  ├─┬ body-parser@1.19.0
  │ ├── bytes@3.1.0
  │ ├── content-type@1.0.4
  │ ├─┬ debug@2.6.9
  │ │ └── ms@2.0.0
  │ ├── depd@1.1.2
  │ ├─┬ http-errors@1.7.2
  │ │ ├── depd@1.1.2 deduped
  │ │ ├── inherits@2.0.3
  │ │ ├── setprototypeof@1.1.1 deduped
  │ │ ├── statuses@1.5.0 deduped
  │ │ └── toidentifier@1.0.0
  │ ├─┬ iconv-lite@0.4.24
  │ │ └── safer-buffer@2.1.2
  │ ├─┬ on-finished@2.3.0
  │ │ └── ee-first@1.1.1
  │ ├── qs@6.7.0
  │ ├─┬ raw-body@2.4.0
  │ │ ├── bytes@3.1.0 deduped
  │ │ ├── http-errors@1.7.2 deduped
  │ │ ├── iconv-lite@0.4.24 deduped
  │ │ └── unpipe@1.0.0
  │ └─┬ type-is@1.6.18
  │   ├── media-typer@0.3.0
  │   └─┬ mime-types@2.1.24
  │     └── mime-db@1.40.0
  ├─┬ cors@2.8.5
  │ ├── object-assign@4.1.1
  │ └── vary@1.1.2
  ├── docopt@0.6.2
  ├─┬ express@4.17.1
  │ ├─┬ accepts@1.3.7
  │ │ ├── mime-types@2.1.24 deduped
  │ │ └── negotiator@0.6.2
  │ ├── array-flatten@1.1.1
  │ ├── body-parser@1.19.0 deduped
  │ ├─┬ content-disposition@0.5.3
  │ │ └── safe-buffer@5.1.2 deduped
  │ ├── content-type@1.0.4 deduped
  │ ├── cookie@0.4.0
  │ ├── cookie-signature@1.0.6
  │ ├── debug@2.6.9 deduped
  │ ├── depd@1.1.2 deduped
  │ ├── encodeurl@1.0.2
  │ ├── escape-html@1.0.3
  │ ├── etag@1.8.1
  │ ├─┬ finalhandler@1.1.2
  │ │ ├── debug@2.6.9 deduped
  │ │ ├── encodeurl@1.0.2 deduped
  │ │ ├── escape-html@1.0.3 deduped
  │ │ ├── on-finished@2.3.0 deduped
  │ │ ├── parseurl@1.3.3 deduped
  │ │ ├── statuses@1.5.0 deduped
  │ │ └── unpipe@1.0.0 deduped
  │ ├── fresh@0.5.2
  │ ├── merge-descriptors@1.0.1
  │ ├── methods@1.1.2
  │ ├── on-finished@2.3.0 deduped
  │ ├── parseurl@1.3.3
  │ ├── path-to-regexp@0.1.7
  │ ├─┬ proxy-addr@2.0.5
  │ │ ├── forwarded@0.1.2
  │ │ └── ipaddr.js@1.9.0
  │ ├── qs@6.7.0 deduped
  │ ├── range-parser@1.2.1
  │ ├── safe-buffer@5.1.2
  │ ├─┬ send@0.17.1
  │ │ ├── debug@2.6.9 deduped
  │ │ ├── depd@1.1.2 deduped
  │ │ ├── destroy@1.0.4
  │ │ ├── encodeurl@1.0.2 deduped
  │ │ ├── escape-html@1.0.3 deduped
  │ │ ├── etag@1.8.1 deduped
  │ │ ├── fresh@0.5.2 deduped
  │ │ ├── http-errors@1.7.2 deduped
  │ │ ├── mime@1.6.0
  │ │ ├── ms@2.1.1 extraneous
  │ │ ├── on-finished@2.3.0 deduped
  │ │ ├── range-parser@1.2.1 deduped
  │ │ └── statuses@1.5.0 deduped
  │ ├─┬ serve-static@1.14.1
  │ │ ├── encodeurl@1.0.2 deduped
  │ │ ├── escape-html@1.0.3 deduped
  │ │ ├── parseurl@1.3.3 deduped
  │ │ └── send@0.17.1 deduped
  │ ├── setprototypeof@1.1.1
  │ ├── statuses@1.5.0
  │ ├── type-is@1.6.18 deduped
  │ ├── utils-merge@1.0.1
  │ └── vary@1.1.2 deduped
  ├─┬ morgan@1.9.1
  │ ├─┬ basic-auth@2.0.1
  │ │ └── safe-buffer@5.1.2 deduped
  │ ├── debug@2.6.9 deduped
  │ ├── depd@1.1.2 deduped
  │ ├── on-finished@2.3.0 deduped
  │ └── on-headers@1.0.2
  └─┬ nefit-easy-commands@3.0.4
    ├── bluebird@3.5.5 deduped
    ├─┬ nefit-easy-core@4.0.0
    │ ├── bluebird@3.5.5 deduped
    │ ├── debug@3.2.6 extraneous
    │ ├── http-string-parser@0.0.5
    │ ├─┬ node-xmpp-client@3.2.0
    │ │ ├── browser-request@0.3.3
    │ │ ├── debug@2.6.9 deduped
    │ │ ├─┬ md5.js@1.3.5
    │ │ │ ├─┬ hash-base@3.0.4
    │ │ │ │ ├── inherits@2.0.3 deduped
    │ │ │ │ └── safe-buffer@5.1.2 deduped
    │ │ │ ├── inherits@2.0.3 deduped
    │ │ │ └── safe-buffer@5.1.2 deduped
    │ │ ├── minimist@1.2.0
    │ │ ├─┬ node-xmpp-core@5.0.9
    │ │ │ ├── @xmpp/jid@0.0.2
    │ │ │ ├─┬ @xmpp/streamparser@0.0.6
    │ │ │ │ ├── @xmpp/xml@0.1.3 deduped
    │ │ │ │ ├── inherits@2.0.3 deduped
    │ │ │ │ └─┬ ltx@2.8.1
    │ │ │ │   └── inherits@2.0.3 deduped
    │ │ │ ├─┬ @xmpp/xml@0.1.3
    │ │ │ │ ├── inherits@2.0.3 deduped
    │ │ │ │ └── ltx@2.8.1 deduped
    │ │ │ ├── debug@2.6.9 deduped
    │ │ │ ├── inherits@2.0.3 deduped
    │ │ │ ├── lodash.assign@4.2.0
    │ │ │ ├── node-xmpp-tls-connect@1.0.1
    │ │ │ └─┬ reconnect-core@0.0.1
    │ │ │   └── backoff@2.3.0
    │ │ ├─┬ request@2.88.0
    │ │ │ ├── aws-sign2@0.7.0
    │ │ │ ├── aws4@1.8.0
    │ │ │ ├── caseless@0.12.0
    │ │ │ ├─┬ combined-stream@1.0.8
    │ │ │ │ └── delayed-stream@1.0.0
    │ │ │ ├── extend@3.0.2
    │ │ │ ├── forever-agent@0.6.1
    │ │ │ ├─┬ form-data@2.3.3
    │ │ │ │ ├── asynckit@0.4.0
    │ │ │ │ ├── combined-stream@1.0.8 deduped
    │ │ │ │ └── mime-types@2.1.24 deduped
    │ │ │ ├─┬ har-validator@5.1.3
    │ │ │ │ ├─┬ ajv@6.10.1
    │ │ │ │ │ ├── fast-deep-equal@2.0.1
    │ │ │ │ │ ├── fast-json-stable-stringify@2.0.0
    │ │ │ │ │ ├── json-schema-traverse@0.4.1
    │ │ │ │ │ └─┬ uri-js@4.2.2
    │ │ │ │ │   └── punycode@2.1.1
    │ │ │ │ └── har-schema@2.0.0
    │ │ │ ├─┬ http-signature@1.2.0
    │ │ │ │ ├── assert-plus@1.0.0
    │ │ │ │ ├─┬ jsprim@1.4.1
    │ │ │ │ │ ├── assert-plus@1.0.0 deduped
    │ │ │ │ │ ├── extsprintf@1.3.0
    │ │ │ │ │ ├── json-schema@0.2.3
    │ │ │ │ │ └─┬ verror@1.10.0
    │ │ │ │ │   ├── assert-plus@1.0.0 deduped
    │ │ │ │ │   ├── core-util-is@1.0.2
    │ │ │ │ │   └── extsprintf@1.3.0 deduped
    │ │ │ │ └─┬ sshpk@1.16.1
    │ │ │ │   ├─┬ asn1@0.2.4
    │ │ │ │   │ └── safer-buffer@2.1.2 deduped
    │ │ │ │   ├── assert-plus@1.0.0 deduped
    │ │ │ │   ├─┬ bcrypt-pbkdf@1.0.2
    │ │ │ │   │ └── tweetnacl@0.14.5 deduped
    │ │ │ │   ├─┬ dashdash@1.14.1
    │ │ │ │   │ └── assert-plus@1.0.0 deduped
    │ │ │ │   ├─┬ ecc-jsbn@0.1.2
    │ │ │ │   │ ├── jsbn@0.1.1 deduped
    │ │ │ │   │ └── safer-buffer@2.1.2 deduped
    │ │ │ │   ├─┬ getpass@0.1.7
    │ │ │ │   │ └── assert-plus@1.0.0 deduped
    │ │ │ │   ├── jsbn@0.1.1
    │ │ │ │   ├── safer-buffer@2.1.2 deduped
    │ │ │ │   └── tweetnacl@0.14.5
    │ │ │ ├── is-typedarray@1.0.0
    │ │ │ ├── isstream@0.1.2
    │ │ │ ├── json-stringify-safe@5.0.1
    │ │ │ ├── mime-types@2.1.24 deduped
    │ │ │ ├── oauth-sign@0.9.0
    │ │ │ ├── performance-now@2.1.0
    │ │ │ ├── qs@6.5.2 extraneous
    │ │ │ ├── safe-buffer@5.1.2 deduped
    │ │ │ ├─┬ tough-cookie@2.4.3
    │ │ │ │ ├── psl@1.2.0
    │ │ │ │ └── punycode@1.4.1 extraneous
    │ │ │ ├─┬ tunnel-agent@0.6.0
    │ │ │ │ └── safe-buffer@5.1.2 deduped
    │ │ │ └── uuid@3.3.2
    │ │ └─┬ ws@1.1.5
    │ │   ├── options@0.0.6
    │ │   └── ultron@1.0.2
    │ ├── promise-queue@2.2.5
    │ ├─┬ sasl-scram-sha-1@1.2.1
    │ │ ├── bitwise-xor@0.0.0
    │ │ ├─┬ create-hash@1.2.0
    │ │ │ ├─┬ cipher-base@1.0.4
    │ │ │ │ ├── inherits@2.0.3 deduped
    │ │ │ │ └── safe-buffer@5.1.2 deduped
    │ │ │ ├── inherits@2.0.3 deduped
    │ │ │ ├── md5.js@1.3.5 deduped
    │ │ │ ├─┬ ripemd160@2.0.2
    │ │ │ │ ├── hash-base@3.0.4 deduped
    │ │ │ │ └── inherits@2.0.3 deduped
    │ │ │ └─┬ sha.js@2.4.11
    │ │ │   ├── inherits@2.0.3 deduped
    │ │ │   └── safe-buffer@5.1.2 deduped
    │ │ ├─┬ create-hmac@1.1.7
    │ │ │ ├── cipher-base@1.0.4 deduped
    │ │ │ ├── create-hash@1.2.0 deduped
    │ │ │ ├── inherits@2.0.3 deduped
    │ │ │ ├── ripemd160@2.0.2 deduped
    │ │ │ ├── safe-buffer@5.1.2 deduped
    │ │ │ └── sha.js@2.4.11 deduped
    │ │ └─┬ randombytes@2.1.0
    │ │   └── safe-buffer@5.1.2 deduped
    │ └── saslmechanisms@0.1.1
    └── require-all@2.2.0

npm ERR! extraneous: ms@2.1.1 /tmp/node_modules/send/node_modules/ms
npm ERR! extraneous: debug@3.2.6 /tmp/node_modules/nefit-easy-core/node_modules/debug
npm ERR! extraneous: qs@6.5.2 /tmp/node_modules/request/node_modules/qs
npm ERR! extraneous: punycode@1.4.1 /tmp/node_modules/tough-cookie/node_modules/punycode

**Comment by robertklep** [comment] 2019-07-11 11:22
Similar to mine, so that's not a cause either.

**Comment by skai21** [comment] 2019-07-11 11:26
I'm trying to think of what could be wrong with the network part, but it's just an:
- Clean installed Raspberry Pi, with domoticz installed.
- Directly connect to LAN port on my Fritzbox Router
- Default XS4ALL config on the Fritzbox, only thing added is port forward for 22 and 8080 to the PI.

I can't seem to find out what this could be, the router doesn't have any firewalling as far as i know. And the Nefit Easy itself is in the same network as the pi, and is able to setup the connection.

**Comment by robertklep** [comment] 2019-07-11 11:28
Do you have another machine in your network that you could try and install the software on?

**Comment by skai21** [comment] 2019-07-11 11:30
i'll try and spin up an linux VM on my PC later today, see if that works

**Comment by skai21** [comment] 2019-07-11 21:12
So.. I got further with the issue..
I installed an Ubuntu server VM, and installed nodejs/easy-server/easy-cli. That worked on another network then my home network, and after that i tried that one on my home network. Also worked.

So i then wiped my Raspberry Pi, and reinstalled it with: 
2019-06-20-raspbian-buster-lite

after the install, I updated the raspberry and ran the installer again. but this raspberry now has exaclty the same issue as before.

So:
Clean install, no other software installed, no services running except for OpenSSH.
Still not working.

Any clue?

**Comment by robertklep** [comment] 2019-07-12 08:16
So the issue seems to be Raspbian? I'll try and see it I can install that particular version on one of my RPi's and see it I can reproduce the problem.

**Comment by skai21** [comment] 2019-07-12 08:21
It seems to be, it is after all an clean install.
I'll try to put another ip-address on the pi, and remove the port redirection to it. That is the only difference i have between my test VM and the PI.

**Comment by robertklep** [comment] 2019-07-12 08:50
Just for my information, what type of RPi do you have?

**Comment by robertklep** [comment] 2019-07-12 09:25
I can reproduce the problem with 2019-06-20-raspbian-buster-lite on my own RPi3.

When I installed Node.js and NPM using `apt-get`, I noticed that for some reason, the NPM version in the repo doesn't match up with the Node.js version in the same repo. So Buster seems a bit unstable to begin with. I tried removing the repo versions and installing the official Node.js ARM package, but that didn't fix the problem.

Then I found this: https://www.debian.org/releases/stable/amd64/release-notes/ch-information.en.html#openssl-defaults

The OpenSSL defaults for Buster are causing the problem, probably because Nefit/Bosch is using either an outdated TLS version or an outdated cipher. The proposed fix for `/etc/ssl/openssl.cnf` fixes the issue with `easy-server`.

**Comment by skai21** [comment] 2019-07-12 12:06
That fixed the problem for me, thank you for the support.

**Closed** 2019-07-12 12:06 UTC

**Comment by chrislader** [comment] 2019-08-21 19:52
@robertklep I got problems as well. Suddenly since a few weeks.

![image](https://user-images.githubusercontent.com/40333466/63463597-cd7c7880-c45d-11e9-9d21-eebc0cfa4650.png)

First I thought it might be something with my password that changed. My old password didnt fit the policy of Bosch. I adjusted it but nothing.

Whitelisted the URL in PiHole as mentioned above (thought maybe this was caused by latest update).

I can't figure out what changed....

**Comment by hoekbrwr** [comment] 2020-01-13 21:04
Took me some headaches, but with this hint to the SSL config file it works now on my Buster too. I assume I am now less safe for all my other stuff too?

**Comment by robertklep** [comment] 2020-01-14 06:44
@hoekbrwr a bit, yes. At least theoretically.

**Comment by hoekbrwr** [comment] 2020-01-16 11:18
I wrote a comment to Bosch about this where I pointed them to this discussion and necessary changes to the settings and the resolution. I am wondering if they at least, will react to it.  We will see.

**Comment by robertklep** [comment] 2020-01-16 11:31
@hoekbrwr they can't fix this on their side unless they force-update the firmware of all devices that are using an outdated TLS setup, which I don't expect they will do. Besides that, strictly from a security point of view, Bosch/Nefit has an additional layer of encryption on top of TLS, so pragmatically speaking, they don't really have a lot to worry about.

Linux/Debian depends on a system-wide configuration for TLS and (AFAIK) the only way to get my (unofficial!) software working is to downgrade the minimal requirements. That's not Bosch/Nefit's fault.

**Comment by TheFons-01** [comment] 2020-12-28 23:58
For what it is worth:
I have followed the wiki page for domoticz to install the nefithttpserver on my pi. 
I have updated all and everything and followed you tip rearding lowering the openssl setting to none and default. 
But all my pm2 logs showed me that I had the authentiction error.
**`nefiteas | XMPP authentication failure`** 
Getting tired of this I replaced the settings of the etc/ssl/openssl.cnf to 
**```
MinProtocol = TLSv1.2
CipherString = DEFAULT@SECLEVEL=2
```**
And presto, after PM2 do a restart of nefiteasyhttpserver,  Easyserver is now running! PM2 logs gives this:
**```
PM2        | 2020-12-29T00:27:04: PM2 log: App [nefiteasyhttpserver:0] online
PM2        | 2020-12-29T00:27:07: PM2 log: App [nefiteasyhttpserver:0] exited with code [1] via signal [SIGINT]
PM2        | 2020-12-29T00:27:07: PM2 log: App [nefiteasyhttpserver:0] starting in -fork mode-
PM2        | 2020-12-29T00:27:07: PM2 log: App [nefiteasyhttpserver:0] online
PM2        | 2020-12-29T00:28:01: PM2 log: Stopping app:nefiteasyhttpserver id:0
PM2        | 2020-12-29T00:28:01: PM2 log: App [nefiteasyhttpserver:0] exited with code [0] via signal [SIGINT]
PM2        | 2020-12-29T00:28:01: PM2 log: pid=4828 msg=process killed
PM2        | 2020-12-29T00:28:01: PM2 log: App [nefiteasyhttpserver:0] starting in -fork mode-
PM2        | 2020-12-29T00:28:01: PM2 log: App [nefiteasyhttpserver:0] online
```**
BUT:
in domoticz the Netfit http plugin still shows in the logging:
**`2020-12-29 00:54:06.388 Error: NefitEasy: Error getting http data!`**
ERGO:
only half of my problem is fixed, Now I still need a solution for the domoticz part for the Nefit plugin. 
Can you help?
